version: '3.8'
services:
  airflow:
    image: my_airflow_image:test_v1
    ports:
      - "8000:8080"
    entrypoint: /app/News-Api-Project/entrypoint.sh
    volumes:
      - airflow-db:/home/airflow/airflow
      - ./other_stuff:/home/airflow/other_stuff
    restart: on-failure

volumes:
  airflow-db: